spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          # 1. DÉFINITION DES ROUTES
          routes:
            - id: auth-service # AJOUT DU TIRET ICI
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3 # Enlève /api, /v1, /auth

# 2. CONFIGURATION DU SERVEUR
server:
  port: 8080

# 3. CONFIGURATION CLIENT EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 4. CONFIGURATION SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "1. Authentification (V1)"
        url: /api/v1/auth/v3/api-docs # La Gateway va appeler cette route, puis Stripper
  api-docs:
    path: /v3/api-docs