spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        mvc: 
          # 1. CONFIGURATION DU CORS
          globalcors:
            cors-configurations:
              '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"

          # 2. DÉFINITION DES ROUTES (Directement sous mvc, sans le mot 'server')
          routes:
            id: auth-service
            uri: lb://auth-service
            predicates:
              Path=/api/v1/auth/**
            filters:
              StripPrefix=2

# 3. CONFIGURATION DU SERVEUR (À la racine, pas sous spring)
server:
  port: 8080

# 4. CONFIGURATION CLIENT EUREKA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# 5. CONFIGURATION SWAGGER / SPRINGDOC
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "1. Authentification (V1)"
        url: /api/v1/auth/v3/api-docs
  api-docs:
    path: /v3/api-docs

# 6. ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"